### PR TITLE
Fix broken github action for updating public IP ranges

### PR DESCRIPTION
**Pull request by chase9**
The Github action to update Microsoft's public IP ranges has been broken since lxml moved a core dependency out to its own package. This PR adds that new package as a dependency for the action. I'm also comitting the updated IP range file which was generated.

### CODE REVIEW

**Comment by chase9** [comment]
@microsoft-github-policy-service agree

**Comment by chase9** [comment]
I also added the missing dep to the Mitre action, which allows the action to run, but there is another issue with the action which causes it to fail. I believe that is beyond the scope of the PR.

**Comment by ashwin-patil** [comment]
Thank you @chase9.

**Comment by chase9** [comment]
Hi @ashwin-patil, you caught me just as I was working on fixing the node depreciation warnings and the failures when there have been no new weekly updates to the IP ranges. I think you have a version in master that is half fixed. My branch now has these fixes. Do you want me to open a new PR?

**Comment by ashwin-patil** [comment]
> Hi @ashwin-patil, you caught me just as I was working on fixing the node depreciation warnings and the failures when there have been no new weekly updates to the IP ranges. I think you have a version in master that is half fixed. My branch now has these fixes. Do you want me to open a new PR?

Got it. Yes, Please open a PR . 
I will keep an eye on the updated actions run. There have been changes on github action bot account as well which may need additional fix.

**Comment by chase9** [comment]
Sounds good, PR opened at #32. Thanks!

**Pull request merged**
